apiVersion: v1
kind: PersistentVolume
metadata:
  name: hls-file-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "hls-file-class"
  nfs:
    path: /home/k8s/nfs/hls-file
    server: 192.168.1.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hls-file-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: "hls-file-class"